### ISSUE TITLE
missing .h files?

### ISSUE THREAD

**Issue by yg2537** [nalinigans/GenomicsDB-R#14]
Tyring to compile the GenomicsDB-R with below error:

checking for /home/marissa/include/genomicsdb.h... no
configure: error: GenomicsDB include files not found
ERROR: configuration failed for package ‘genomicsdb’

is that due to the .h files is mssing in src folder?

Thanks!

**Comment by nalinigans** [comment]
As mentioned in the README, these bindings are only for queries and  you will have to build/install GenomicsDB first, you can follow instructions here - https://github.com/GenomicsDB/GenomicsDB/tree/master/scripts. That said, it's been awhile since we looked at the R bindings and things may be out of sync with the main GenomicsDB branch. 

@yg2537, can you wait a day or two for us to take a look and update the bindings to make it usable? Thanks.

**Comment by nalinigans** [comment]
Closing this for now. Please let me know if you still find issues with using the bindings. Thanks.
